name: CI

on: [push]

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Tests
        run: npm run test
